### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np

numeros = np.random.randint(1, 51, size=10)

media = np.mean(arr)
desvio_padrao = np.std(arr)

print("Lista: ", numeros)
print("Média: ", media)
print("Desvio Padrão: ", desvio_padrao)

Array:  [ 9  6 15 18 23 36  8 32 49 35]
Média:  21.3
Desvio Padrão:  14.394790724425276


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
numeros = np.random.rand(10)

raiz = np.sqrt(numeros[numeros <= 0.5])

print("Lista: ", numeros)
print("Raiz dos menores de 0.5: ", raiz)

Lista:  [0.86275173 0.60998143 0.82846309 0.4319269  0.74738958 0.69873167
 0.82413181 0.05236449 0.08874344 0.35452848]
Raiz dos menores de 0.5:  [0.65721146 0.22883288 0.29789837 0.59542295]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
matriz_3D = np.random.randint(1, 10, size=(3, 3, 3))

matriz_maximo = np.max(matriz_3D, axis=2)

print(f"Matriz 3D:\n{matriz_3D}")
print(f"\nMatriz 2D com valor máximo:\n{matriz_maximo}")

Matriz 3D:
[[[6 5 1]
  [3 9 5]
  [4 1 8]]

 [[6 5 6]
  [3 7 3]
  [6 6 6]]

 [[9 7 9]
  [7 4 8]
  [9 7 1]]]

Matriz 2D com valor máximo:
[[6 9 8]
 [6 7 6]
 [9 8 9]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
matriz = np.random.randint(1, 100, size=(5, 5))
media = np.mean(matriz, axis=1)
matriz_final = matriz - media.reshape((-1,1))

print(f"Matriz:\n{matriz}")
print(f"\nMedia:\n{media.reshape((-1,1))}")
print(f"\nMatriz - Media:\n{matriz_final}")

Matriz:
[[12 11 48 23 95]
 [36 26 38 73 62]
 [96 42 31 95 94]
 [15 21 37 15  6]
 [52 67 26  3 15]]

Media:
[[37.8]
 [47. ]
 [71.6]
 [18.8]
 [32.6]]

Matriz - Media:
[[-25.8 -26.8  10.2 -14.8  57.2]
 [-11.  -21.   -9.   26.   15. ]
 [ 24.4 -29.6 -40.6  23.4  22.4]
 [ -3.8   2.2  18.2  -3.8 -12.8]
 [ 19.4  34.4  -6.6 -29.6 -17.6]]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
matriz = np.random.randint(1, 100, size=(4, 4))

med_diag_1 = np.mean(np.diag(matriz))
desv_diag_1 = np.std(np.diag(matriz))

med_diag_2 = np.mean(np.diag(np.fliplr(matriz)))
desv_diag_2 = np.std(np.diag(np.fliplr(matriz)))

print(f"Matriz:\n{matriz}")

print(f"\nDiagonal Principal")
print(f"Media: {med_diag_1}")
print(f"Desvio Padrão: {desv_diag_1}")

print(f"\nDiagonal Secundária")
print(f"Media: {med_diag_2}")
print(f"Desvio Padrão: {desv_diag_2}")

Matriz:
[[25 58 83 79]
 [92 39 98 44]
 [ 4 81  5 21]
 [84 25 38 67]]

Diagonal Principal
Media: 34.0
Desvio Padrão: 22.561028345356956

Diagonal Secundária
Media: 85.5
Desvio Padrão: 7.433034373659253
